require(game.ServerScriptService.Modules.Bootstrap.NetworkSetupService)
require(game.ServerScriptService.Modules.Economics.CurrencyService)
require(game.ServerScriptService.Modules.Core.InventoryService)

require(game.ServerScriptService.Modules.Core.PlayerConnectionService)

require(game.ServerScriptService.Modules.ControllerService)

require(game.ServerScriptService.Modules.Gameplay.KillObjectService)